### ISSUE TITLE
[Doc] - Revamp installation pages

### ISSUE THREAD

**Issue by juadk** [epinio/docs#129]
Already discussed with @nunix and @mmartin24 

When you land on the documentation website, I find very confusing the way to get the installation instructions for Epinio.
![image](https://user-images.githubusercontent.com/6025636/171869803-adf65bfe-1e5b-4b7a-9f46-11e815e8b22f.png)

You have to click on Installation to print the instructions. 
As a user (and it already happened with newcomer), I would click on the down arrow next to installation and then, click on Install Epinio CLI because I see Install Epinio there.
And it will result with a bad experience because you will install the epinio CLI and it's useless without an epinio server instance.
I would prefer something like:
```
Installation 
    Install Epinio
    Install Epinio CLI
```

**Comment by nunix** [comment]
New menu has now no pages "embedded" in the main categories.
