### ISSUE TITLE
[DOCS] - Fix helm chart links on 1.0.0 pointing to 0.7.1

### ISSUE THREAD

**Issue by mmartin24** [epinio/docs#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After 1.0.0 release some helm chart links are still poinint to 0.7.1 as can be seen:
https://docs.epinio.io/howtos/install_epinio_on_rancher_desktop
![image](https://user-images.githubusercontent.com/37271841/175538833-1b424750-52f7-474a-bf79-1bdfaccbf5ce.png)

There are a few examples in the 'How to pages' but potentially can be more:

- https://docs.epinio.io/howtos/install_epinio_on_rancher
- https://docs.epinio.io/howtos/install_epinio_on_rke
- https://docs.epinio.io/howtos/install_epinio_on_k3s
- https://docs.epinio.io/howtos/install_epinio_on_rancher_desktop
- https://docs.epinio.io/howtos/install_epinio_on_k3d
- 

### Expected Behavior

They should point to 1.0.0 (24 Jun, 2022)

### Environment

```markdown
- OS:
- Architecture:
- Epinio Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by jimmykarily** [comment]
Let's try the instructions  with `v1.0.0` and if it still works we remove the warning. The page was written before we had versioned docs, now we do so we just have to make sure they docs are up to date with the release they belong to.

**Comment by mmartin24** [comment]
Note, I tried the instructions mentioned above to install RD in v1.0.0 and it worked:


![Image](https://user-images.githubusercontent.com/37271841/177278230-7f99aa10-130a-4e3c-9994-604e406d1f3b.png)
