### ISSUE TITLE
Improve epinio.io home page

### ISSUE THREAD

**Issue by jimmykarily** [epinio/docs#167]
@catherineluse suggested the following improvements to the epinio.io front page:

- put the epinio push command at the top, so you can see it without scrolling down. The top says in words "go from Code to URL in one step" but it isn't clear what that step is, as the epinio push isn't actually mentioned until the bottom of the page.
- we should mention that you don't need to build the application container image yourself
- we should mention that it comes with a UI
- The install steps on the landing page have too many steps, so at a glance it looks like a lot. I think the steps should be more like:
    1. Get access to a Kubernetes cluster 
    2. Install Epinio in the cluster with Helm
    3. Log in to the cluster with epinio login
    4. Do epinio push (or whatever is needed to get to epinio push.)
It should just link to docs for details instead of trying to put everything on the landing page

We should also  mention a newer (supported) version of cert-manager (if at all)

**Comment by andreas-kupries** [comment]
The title block is so large that scrolling seems to be always required. The formatting seems to come from whatever process generates the site from the sources. In the `_index.html` it is not specified as html, but as a key/value heading section separated from the main HTML by yaml-style document separators.

**Comment by andreas-kupries** [comment]
PR @ https://github.com/epinio/epinio.io/pull/23
