### ISSUE TITLE
[docs] Missing initial step `epinio settings update-ca` for epinio CLI

### ISSUE THREAD

**Issue by thehejik** [epinio/docs#189]
This command `epinio settings update-ca` have to be called after downloading epinio binary and before calling `epinio login ...` otherwise user is getting an Error `x509: signed by unknown authority` when doing `epinio push ...`

Good place would be probably https://docs.epinio.io/tutorials/quickstart#login and also on the cli reference page https://docs.epinio.io/references/settings#commands

**Comment by enrichman** [comment]
That's not completely true. The command is used to "refresh" old settings that contains an expired certificate. It happens when you recreate a cluster, or the certificate is renewed.

**Comment by thehejik** [comment]
Thanks, so this is probably needed only when the epinio has been reinstalled on the environment where it was installed/initialized before already.
