### ISSUE TITLE
helm install traefik fails: not found

### ISSUE THREAD

**Issue by nathanweeks** [epinio/docs#198]
The helm chart tarball https://helm.traefik.io/traefik/traefik-10.3.4.tgz listed in the Traefik installation instructions no longer exists at that URL

https://github.com/epinio/docs/blob/1a250297f2ed24b763893c4bbb5572da41bffd4e/docs/installation/install_epinio.md?plain=1#L35-L42

**Comment by thehejik** [comment]
@nunix This is how we install Traefik in CI on EKS, there is no version resolution so we use the latest one there. https://github.com/epinio/epinio/blob/main/acceptance/install/suite_test.go#L61

**Comment by thehejik** [comment]
Documentation was updated.
