### ISSUE TITLE
Describe how to specify an ingressClass for workload only

### ISSUE THREAD

**Issue by thehejik** [epinio/docs#217]
According to https://github.com/epinio/epinio/issues/1954 user may define a ingressClass for workload only, this is probably not covered by documentation.

* Epinio itself and its Workload uses the `default` ingressClass if not defined by `--set ingress.ingressClassName=traefik`
* NEW  in addition users may define also an ingressClass for epinio Workload only by `--set server.ingressClassName=nginx`

**Comment by andreas-kupries** [comment]
@thehejik @abonillabeeche

It actually is documented, in the Customization category of the References section.
See `docs/references/customization/lb.md`.
IOW https://docs.epinio.io/references/customization/lb

**Comment by andreas-kupries** [comment]
Now thinking about how to write a how to for this.
