### ISSUE TITLE
Test and Document splitting control plane and workload 

### ISSUE THREAD

**Issue by agracey** [epinio/docs#229]
We should test and document a configuration where the control plane is being exposed through one ingress class and the workload is exposed through another. This can help increase security by allowing for control plane to be on an internal only network instead of exposing to the internet. 

Solution requirements:
- Traffic is split between different domains
- Developers should be easily able to specify which ingress/network to expose app on
- App exports should work as expected

Out of scope:
- Epinio would not provide ingress or IngressClasses
- Epinio would not control any networking before ingress (security groups for example)

**Comment by thehejik** [comment]
This seems to be addressed already via https://github.com/epinio/docs/issues/217

**Comment by thehejik** [comment]
@agracey we can already specify ingresses for epinio components and for workload, but we would probably need also a way how to specify a dedicated domains for epinio component and workload. Is that assumption correct? Currently we offer only one `global.domain` which is used for both.

**Comment by thehejik** [comment]
As a workaround users may define a custom route for a workload using different domain:
![image](https://user-images.githubusercontent.com/12828077/226912785-98ac9057-b224-4983-9311-1c2a8380cab2.png)

**Comment by thehejik** [comment]
This is how I tested on k3s `v1.24.6+k3s1`

* create an ingressClass dedicated to Epinio applications:
```
$ cat <<EOF | kubectl apply -f -                                                                                                                                                        
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
spec:
  controller: traefik.io/ingress-controller
EOF
```
* install Epinio v1.7.1 and define the application ingress there:
```
$ helm upgrade --install epinio --namespace epinio epinio/epinio --set server.ingressClassName=traefik --set global.domain=1.2.3.4.nip.io --create-namespace
```
* login and push when specifying the custom `--route` domain:
```
$ epinio login -u admin -p *** --trust-ca https://epinio.1.2.3.4.nip.io
$ epinio app push -n sample -p ./sample-app/ --route sample.1.2.3.4.omg.howdoi.website
```
* verify if the correct ingressClass for the application is used and the app is reachable.
```
$ kubectl get ingress -A
NAMESPACE       NAME             CLASS     HOSTS                               ADDRESS   PORTS     AGE
epinio          dex              <none>    auth.1.2.3.4.nip.io                 1.2.3.4   80, 443   10m
epinio          epinio           <none>    epinio.1.2.3.4.nip.io               1.2.3.4   80, 443   10m
workspace       rsample-samplexx traefik   sample.1.2.3.4.omg.howdoi.website   1.2.3.4   80, 443   5m59s
```

The next step for hardened epinio deployment would be probably about setting up a k8s NetworkPolicy for preventing communication of epinio components with outside. This is out of scope for this Issue, more info [here](https://kubernetes.io/docs/concepts/services-networking/network-policies/)

**Comment by thehejik** [comment]
Tested and documented, close.
