### ISSUE TITLE
Consistent use of How-to

### ISSUE THREAD

**Issue by jhkrug** [epinio/docs#262]
Make sure How-to is used consistently throughout the documentation set. As per the [MS style guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/h/how-how-to).

**Comment by jhkrug** [comment]
We have 4 variants, ignoring the simple use of 'how to' in the text. We only want 'How-to'.

```
find . -type f \( -name '*.json' -o -name '*.md' \) -exec grep -Eo 'H[Oo][Ww][- _]*[Tt][Oo]' {} \; | sort -u
How to
How To
How-To
HowTo
```

**Comment by andreas-kupries** [comment]
Simplifying `grep -Eo 'H[Oo][Ww][- _]*[Tt][Oo]'`
as `grep --ignore-case -Eo 'HOW[- _]*TO'`
should also catch any full lower case uses, like `how-to`, etc., should they exist.

**Comment by jhkrug** [comment]
Thanks @andreas-kupries there seem to be a few of those too.
