### ISSUE TITLE
Document how to use Epinio in Rancher

### ISSUE THREAD

**Issue by jimmykarily** [epinio/docs#31]
The docs should include the information from here: https://github.com/epinio/ui/blob/dev/README.md

**Comment by juadk** [comment]
You are talking about the Epinio UI but should we also include how to deploy Epinio with the Rancher market place, I mean, adding the helm repo, fill fields to customize your deployment etc
Maybe we can do it in another card to avoid a big doc task :-) WDYT?

**Comment by juadk** [comment]
Anyway, I think we need a huge doc update. I can still see some calls to `epinio install`

**Comment by jimmykarily** [comment]
Maybe also mention at least one combination of UI that is known to work with a specific version of Epinio
