### ISSUE TITLE
Require RWX/ReadWriteMany storage on multi-node clusters

### ISSUE THREAD

**Issue by thehejik** [epinio/docs#325]
In light of https://github.com/epinio/epinio/issues/2605 we should `require` RWX storage provisioner on multi-node k8s clusters. RWO is still acceptable on single-node k8s clusters.

So far we say just `preferably RWX` here https://docs.epinio.io/installation/install_epinio#dynamic-storage-provisioner but on multi-node this seems to be mandatory at least for export application abilities from Epinio.

**Comment by enrichman** [comment]
Let's see if we can fix the issue on the Epinio side.

**Comment by thehejik** [comment]
Not needed anymore, resolved by https://github.com/epinio/epinio/issues/2605
