### ISSUE TITLE
Update install docs, versions, processes

### ISSUE THREAD

**Issue by jhkrug** [epinio/docs#332]
The installation docs need another iteration. Paying attention to version numbers. They look a bit old. Also re-validate process and procedures still working.

I'll work through this with @mmartin24 to improve.

Prompted by Slack conversation:

https://suse.slack.com/archives/C02DBSHPC2V/p1695979562977679

**Comment by mmartin24** [comment]
Thanks @jhkrug .
Some data here for the update regarding page: https://docs.epinio.io/installation/other_inst_scenarios/install_epinio_on_rancher_desktop

The last test from us was done on `Rancher Desktop 1.9.1` using `Kubernetes version v1.26.5`. These values would need to be added on top of others and would be manually done per release.
- Epinio helm chart targeted was `v1.10.0. This part would need to be automatically updated.

Aside from this, I think that on the installation process box, this line could be removed...
https://github.com/epinio/docs/blob/8503f72eb39a07f13de098ae9f665cd7aee1892c/versioned_docs/version-1.10.0/installation/other_inst_scenarios/install_epinio_on_rancher_desktop.md?plain=1#L53

 
... in favor of this installation process (but it would be wise to have another pair of eyes here):
```
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager  \
    --set installCRDs=true \
    --set extraArgs={--enable-certificate-owner-ref=true} \
    --create-namespace
```
