### ISSUE TITLE
Fix docs refering to old installer

### ISSUE THREAD

**Issue by jimmykarily** [epinio/docs#34]
For example here: https://docs.epinio.io/installation/install_epinio_on_k3d.html#install-epinio-on-the-cluster

It's in many places

**Comment by jimmykarily** [comment]
other: https://docs.epinio.io/explanations/detailed-push-process.html#additional-things (`git grep -i "system domain"`)

**Comment by andreas-kupries** [comment]
@jimmykarily 

> For example here: https://docs.epinio.io/installation/install_epinio_on_k3d.html#install-epinio-on-the-cluster
> It's in many places

I do not see a reference to the old installer here nor in the pages reachable from that section.
I suspect that one of the rewrites in the last month mooted this.
