### ISSUE TITLE
Use numbered prefix in filenames

### ISSUE THREAD

**Issue by enrichman** [epinio/docs#36]
While going through the doc files it's hard to understand which file matches just from the name.

Since they are numbered paragraph I would suggest to rename files and folders with a prefixed number.
I've done this in the past and I found it useful.

i.e.:

At the moment the index is written like this:

```markdown
- [Introduction](introduction.md)
- [Quick Start](tutorials/quickstart.md)
- [Installation](installation/installation.md)
  - [System Requirements](installation/system_requirements.md)
  - [Method 1: Install Epinio and automatically install dependencies](installation/install_epinio_auto.md)
  - [Method 2: Install Epinio and manually install dependencies](installation/install_epinio_manual.md)
  - [Install Epinio cli](installation/install_epinio_cli.md)
...
```
while the files are unordered

```
src/
├── installation/
│   ├── install_epinio_auto.md
│   ├── install_epinio_cli.min.md
│   ├── install_epinio_manual.md
│   ├── installation.md
│   └── system_requirements.md
├── tutorials/
│   └── quickstart.md
└── introduction.md
```

I would suggest to modify it like this:

```
src/
├── 01_tutorials/
│   └── 00_quickstart.md
├── 02_installation/
│   ├── 00_installation.md
│   ├── 01_system_requirements.md
│   ├── 02_install_epinio_auto.md
│   ├── 03_install_epinio_manual.md
│   └── 04_install_epinio_cli.min.md
└── 00_introduction.md
```

**Comment by nunix** [comment]
The structure has just been updated and adding number, while practical, would have created a lot more work to maintain in the long run.

We can discuss this point further, but I would suggest we keep it simple and the order on the docs site shouldn't be "re-adapted" to the files themselves.

**Comment by nunix** [comment]
Since the docs have been migrated to Docusaurus, this issue is obsolete.
