### ISSUE TITLE
Docs structure: re-apply the Divio structure 

### ISSUE THREAD

**Issue by nunix** [epinio/docs#59]
### Is your feature request related to a problem?

The current docs structure is based on the Divio documentation structure, however some areas have started to be mixed up.

### Solution you'd like

Re-apply the Divio documentation structure to the docs and have the different topics re-ordered.

Also, whenever possible, add a Next Steps section to docs in order to provide the reader with a "suggested reading path".

### Alternatives you've considered

N/A

**Comment by nunix** [comment]
While the majority of the structure is in place, here is my suggestion for making it more adapted to Divio documentation structure (it will bring a better cohesion of the docs).

Main sections:

| Section | Type | Current placement | New placement | Comment |
| -------- | ----- | --------------------- | ----------------- | ----------- |
| Introduction | main |  root | root | no change |
| Quick Start | main | root | root | no change |
| Installation | main | root | root | no change |
| System Requirements | sub | Installation | Reference | The System requirements should be moved as a reference as they might be different depending on the Kubernetes cluster used |
| Method 1 | sub | Installation | Installation | The generic installation method should stay here |
| Method 2 | sub | Installation | Installation | The generic installation method should stay here |
| Rancher | sub | Installation | HowTos | This installation addresses a specific case and should be considered as solving a "problem"/question |
| CLI | sub | Installation | Installation | The generic installation method should stay here |
| Custom DNS | sub | Installation | Installation | The generic installation method should stay here |
| Magic DNS | sub | Installation | Installation | The generic installation method should stay here |
| Public Clouds | sub | Installation | HowTos | The current documentation might be split, where the requirements would move to System requirements > Cloud providers, and like the local Kubernetes clusters, each cloud should have its page |
| RKE2 | sub | Installation | HowTos | This installation addresses a specific case and should be considered as solving a "problem"/question |
| K3d | sub | Installation | HowTos | This installation addresses a specific case and should be considered as solving a "problem"/question |
| K3s | sub | Installation | HowTos | This installation addresses a specific case and should be considered as solving a "problem"/question |
| Rancher Desktop | sub | Installation | HowTos | This installation addresses a specific case and should be considered as solving a "problem"/question |
| Minikube | sub | Installation | HowTos | This installation addresses a specific case and should be considered as solving a "problem"/question |
| Wordpress | sub | Installation | HowTos | This installation addresses a specific case and should be considered as solving a "problem"/question |
| Uninstall | main | root | Installation | While this is an important topic, I think it belongs to the Installation section as it's part of the "Epinio app lifecycle" |
| Explanations | main |  root | root | no change |
| Advanced topics | sub |  Explanations | Explanations | no change |
| Configuration | sub |  Explanations | Reference | The configuration describes the generic settings and should be considered as a reference |
| Detailed Push Process | sub |  Explanations | Explanations | no change |
| Principles | sub |  Explanations | Explanations | no change |
| Security | sub |  Explanations | Explanations | no change |
| Windows  | sub |  Explanations | HowTos | While it's not explaining an installation method, it still is a specific case |
| HowTos | main |  root | root | no change |
| overall | sub | HowTos | HowTos | no change |
| Reference | main |  root | root | no change |
| overall | sub | Reference | Reference | no change |

Please note that currently we don't have a `Tutorial` section, however I thought of `Installation` as part of it. Still, the installation is a very important part and it makes total sense to keep it at `root` level.

Any comments are very welcome and please note that I addressed the sections by looking at the current content and thought of the potential modifications it will get.

**Comment by olblak** [comment]
The "overall" section seems a bit weird to me in the reference category but my understanding of "reference" is that it should be exhaustive and overall is an overview.
But it's just a feeling

**Comment by nunix** [comment]
@olblak the "overall" on my first post was to mention the current pages 😓 ... it came out weird on the ASCII tree indeed, sorry
