### ISSUE TITLE
Document requirements for custom helm chart

### ISSUE THREAD

**Issue by agracey** [epinio/docs#60]
Note: Quite a bit of the servers' operation, namely around workloads, assumes the presence of a deployment resource, and/or, and/or ingress. To keep things simple enough now it is assumed that even a custom chart will provide these three resources.

_Originally posted by @andreas-kupries in https://github.com/epinio/epinio/issues/1224#issuecomment-1046963963_

**Comment by andreas-kupries** [comment]
@agracey I believe that https://docs.epinio.io/references/customization/appcharts fulfills your request.
