### ISSUE TITLE
Add documentation on how to configure buildpacks

### ISSUE THREAD

**Issue by manno** [epinio/docs#71]
Epinio uses buildpacks primarily to build workloads. 

Other projects have a lot of documentation around using specific buildpacks, for languages:

* https://docs.cloudfoundry.org/buildpacks/go/index.html

Others describe mainly how to use buildpacks:
* https://buildpacks.io/docs/app-developer-guide/build-an-app/
* https://dokku.com/docs/deployment/builders/cloud-native-buildpacks/
* https://dokku.com/docs/deployment/builders/herokuish-buildpacks/
* https://skaffold.dev/docs/pipeline-stages/builders/buildpacks/

**Comment by jimmykarily** [comment]
Relevant: [#601](https://github.com/epinio/epinio/issues/601)

**Comment by andreas-kupries** [comment]
Wide and vague. More an epic. No actionable points (details of what to write)
