### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by jimmykarily** [epinio/docs#74]
Our docs have a lot of outdated information. Let's fix what we can.

- Installation
- Explanations
- Howtos

https://github.com/epinio/docs/pull/70

**Comment by juadk** [comment]
Today, I've tested and updated these scenarios:

- Minikube
- K3d
- Rancher Desktop
- RKE2

I did my tests with the latest version of every component.

**Comment by juadk** [comment]
Manual deployment on GKE: ✅ 
Create GKE cluster, install traefik + cert-manager, update DNS and deploy Epinio.
