### ISSUE TITLE
Preview Documentation site

### ISSUE THREAD

**Issue by jimmykarily** [epinio/docs#87]
When we make big changes in documentation (like [switching to docusaurus](https://github.com/epinio/docs/issues/69) for example), it's nice if we can see the result before we merge. [netlify](https://www.netlify.com/) or similar could be useful here.

## Acceptance Criteria

- When a PR is opened in `epinio/docs` there is a URL that serves the rendered result.

**Comment by jimmykarily** [comment]
> We could publish with Epinio on Digital Oceansmile

That's also an option :)

**Comment by nunix** [comment]
I'll check what's best indeed, right now we do have a Netlify account, so configuration is up next.

**Comment by jimmykarily** [comment]
done
